"""initial schema

Revision ID: cfe093781e86
Revises: 
Create Date: 2026-09-28 07:41:36.400296
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Our custom Embedding TypeDecorator (pgvector Vector on Postgres, JSON
# elsewhere). Autogenerate emits the class path, so it must be importable.
from app.db.models import Embedding  # noqa: F401


revision: str = 'cfe093781e86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before any Vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('task_name', sa.String(length=60), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_business_id'), 'agent_tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_conversation_id'), 'agent_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_persona_id'), 'agent_tasks', ['persona_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_request_id'), 'agent_tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_task_name'), 'agent_tasks', ['task_name'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_business_id'), 'agent_tool_calls', ['business_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_conversation_id'), 'agent_tool_calls', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_created_at'), 'agent_tool_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_persona_id'), 'agent_tool_calls', ['persona_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_request_id'), 'agent_tool_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_task_id'), 'agent_tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool'), 'agent_tool_calls', ['tool'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_business_id'), 'audit_log', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_request_id'), 'audit_log', ['request_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('monthly_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_workspace_id'), 'businesses', ['workspace_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('account_id', sa.String(length=120), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider', name='uq_integration_provider')
    )
    op.create_index(op.f('ix_integrations_business_id'), 'integrations', ['business_id'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_table('persona_overrides',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=True),
    sa.Column('autonomy', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'persona_id', name='uq_persona_override')
    )
    op.create_index(op.f('ix_persona_overrides_persona_id'), 'persona_overrides', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_overrides_workspace_id'), 'persona_overrides', ['workspace_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_business_id'), 'usage_records', ['business_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_task_id'), 'usage_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_usage_records_workspace_id'), 'usage_records', ['workspace_id'], unique=False)
    op.create_table('brand_memory_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False, comment='voice_example|visual_style|offer|audience|competitor_note|learning|reference_analysis'),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Embedding(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_memory_items_business_id'), 'brand_memory_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_brand_memory_items_campaign_id'), 'brand_memory_items', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_brand_memory_items_created_at'), 'brand_memory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_brand_memory_items_kind'), 'brand_memory_items', ['kind'], unique=False)
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('visual_style', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('key_offers', sa.JSON(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_business_id'), 'brand_profiles', ['business_id'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('objective', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=60), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('meta_campaign_id', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_business_id'), 'campaigns', ['business_id'], unique=False)
    op.create_index(op.f('ix_campaigns_meta_campaign_id'), 'campaigns', ['meta_campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_business_id'), 'conversations', ['business_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('task_name', sa.String(length=60), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('style_spec', sa.JSON(), nullable=True),
    sa.Column('reference_analysis_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_business_id'), 'creatives', ['business_id'], unique=False)
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_campaign_id'), 'insights', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_insights_created_at'), 'insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_insights_severity'), 'insights', ['severity'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_task_id'), 'messages', ['task_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('insight_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('persona_id', sa.String(length=64), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('estimated_impact', sa.String(length=200), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_action_type'), 'recommendations', ['action_type'], unique=False)
    op.create_index(op.f('ix_recommendations_campaign_id'), 'recommendations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_recommendations_insight_id'), 'recommendations', ['insight_id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_insight_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_campaign_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_action_type'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_messages_task_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_insights_severity'), table_name='insights')
    op.drop_index(op.f('ix_insights_created_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_campaign_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_business_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_conversations_business_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_meta_campaign_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_business_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_brand_profiles_business_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_brand_memory_items_kind'), table_name='brand_memory_items')
    op.drop_index(op.f('ix_brand_memory_items_created_at'), table_name='brand_memory_items')
    op.drop_index(op.f('ix_brand_memory_items_campaign_id'), table_name='brand_memory_items')
    op.drop_index(op.f('ix_brand_memory_items_business_id'), table_name='brand_memory_items')
    op.drop_table('brand_memory_items')
    op.drop_index(op.f('ix_usage_records_workspace_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_task_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_business_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_persona_overrides_workspace_id'), table_name='persona_overrides')
    op.drop_index(op.f('ix_persona_overrides_persona_id'), table_name='persona_overrides')
    op.drop_table('persona_overrides')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_business_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_businesses_workspace_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_audit_log_request_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_business_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_tool_calls_tool'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_task_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_request_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_persona_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_created_at'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_conversation_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_business_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_agent_tasks_task_name'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_request_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_persona_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_conversation_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_business_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
